version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - wb

  frontend:
    image: rkddlfah02/wbfront:test
    container_name: frontend
    networks:
      - wb

  backend:
    image: rkddlfah02/wbbackend:test
    container_name: server
    networks:
      - wb
    volumes:
      - ./images:/whereball/src/main/resources/static/images

networks:
  wb:
